### ISSUE TITLE
Subscribing to new messages

### ISSUE THREAD

**Issue by dbrgn** [nyantec/rust-journald#1]
Hi, thanks for this crate! Are you aware of a way to subscribe to incoming journal messages without having to implement some kind of busy-waiting loop?

Maybe systemd allows to create some kind of streaming socket that we could read asynchronously with Tokio?

My use case would be a small program that subscribes to the logs of a list of units and notifies the user if certain patterns are detected (e.g. log level or a regex match).

**Comment by dbrgn** [comment]
Ah, it seems that `rust-systemd` can do that: http://codyps.com/docs/systemd/x86_64-unknown-linux-gnu/stable/systemd/journal/struct.Journal.html#method.await_next_record

What is the relation of this crate to `rust-systemd`? Is it a fork?

**Comment by asmuth** [comment]
We are not the authors of this code, it is just parts of the code from the original journald cargo extract and brought into a working state. The original cargo gave us a lot of grief because it would return records in seemingly random order. Note that the way you talk to journald is via a C API. I'm sure there is a socket in there somwhere, but it is hidden behind the sd-journal C API. So any facility for non blocking reads would have to be already exposed by that API (https://www.freedesktop.org/software/systemd/man/sd-journal.html).

**Comment by dbrgn** [comment]
Thanks for the information :slightly_smiling_face:
